<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('inbodies', function (Blueprint $table) {
            $table->id();
            $table->string('identification_card_number')->comment('เลขบัตรประชาชน 13 หลัก');
            $table->decimal('height')->comment('ส่วนสูง');
            $table->string('gender')->comment('เพศ');
            $table->decimal('age')->comment('อายุ');
            $table->decimal('test_date_time')->comment('วันที่/เวลาที่ตรวจ');
            $table->decimal('weight')->comment('น้ำหนัก');
            $table->decimal('lower_limit_weight_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำหนัก)');
            $table->decimal('upper_limit_weight_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำหนัก)');
            $table->decimal('tbw_total_body_water')->comment('น้ำในร่างกายทั้งหมด');
            $table->decimal('lower_limit_tbw_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำในร่างกายทั้งหมด)');
            $table->decimal('upper_limit_tbw_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำในร่างกายทั้งหมด)');
            $table->decimal('icw_intracellular_water')->comment('น้ำภายในเซลล์');
            $table->decimal('lower_limit_icw_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายในเซลล์)');
            $table->decimal('upper_limit_icw_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายในเซลล์)');
            $table->decimal('ecw_extracellular_water')->comment('น้ำภายนอกเซลล์');
            $table->decimal('lower_limit_ecw_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายนอกเซลล์)');
            $table->decimal('upper_limit_ecw_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายนอกเซลล์)');
            $table->decimal('protein')->comment('โปรตีน');
            $table->decimal('lower_limit_protein_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติโปรตีน)');
            $table->decimal('upper_limit_protein_normal_range')->comment('ค่าสูงสุด (ช่วงปกติโปรตีน)');
            $table->decimal('minerals')->comment('แร่ธาตุ');
            $table->decimal('lower_limit_minerals_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติแร่ธาตุ)');
            $table->decimal('upper_limit_minerals_normal_range')->comment('ค่าสูงสุด (ช่วงปกติแร่ธาตุ)');
            $table->decimal('bfm_body_fat_mass')->comment('มวลไขมันในร่างกาย');
            $table->decimal('lower_limit_bfm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลไขมันในร่างกาย)');
            $table->decimal('upper_limit_bfm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลไขมันในร่างกาย)');
            $table->decimal('slm_soft_lean_mass')->comment('มวลไร้ไขมันส่วนเนื้อเยื่ออ่อน');
            $table->decimal('lower_limit_slm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลไร้ไขมันส่วนเนื้อเยื่ออ่อน)');
            $table->decimal('upper_limit_slm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลไร้ไขมันส่วนเนื้อเยื่ออ่อน)');
            $table->decimal('ffm_fat_free_mass')->comment('มวลไร้ไขมัน');
            $table->decimal('lower_limit_ffm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลไร้ไขมัน)');
            $table->decimal('upper_limit_ffm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลไร้ไขมัน)');
            $table->decimal('smm_skeletal_muscle_mass')->comment('มวลกล้ามเนื้อโครงร่าง');
            $table->decimal('lower_limit_smm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลกล้ามเนื้อโครงร่าง)');
            $table->decimal('upper_limit_smm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลกล้ามเนื้อโครงร่าง)');
            $table->decimal('bmi_body_mass_index')->comment('ดัชนีมวลกาย');
            $table->decimal('lower_limit_bmi_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติของดัชนีมวลกาย)');
            $table->decimal('upper_limit_bmi_normal_range')->comment('ค่าสูงสุด (ช่วงปกติของดัชนีมวลกาย)');
            $table->decimal('pbf_percent_body_fat')->comment('เปอร์เซ็นต์ไขมันในร่างกาย');
            $table->decimal('lower_limit_pbf_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติเปอร์เซ็นต์ไขมันในร่างกาย)');
            $table->decimal('upper_limit_pbf_normal_range')->comment('ค่าสูงสุด (ช่วงปกติเปอร์เซ็นต์ไขมันในร่างกาย)');
            $table->decimal('lean_mass_of_right_arm')->comment('มวลไร้ไขมันของแขนขวา');
            $table->decimal('lower_limit_lean_mass_of_right_arm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลไร้ไขมันของแขนขวา)');
            $table->decimal('upper_limit_lean_mass_of_right_arm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลไร้ไขมันของแขนขวา)');
            $table->decimal('lean_mass_percent_of_right_arm')->comment('เปอร์เซ็นต์มวลไร้ไขมันของแขนขวา');
            $table->decimal('lean_mass_of_left_arm')->comment('มวลไร้ไขมันของแขนซ้าย');
            $table->decimal('lower_limit_lean_mass_of_left_arm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลไร้ไขมันของแขนซ้าย)');
            $table->decimal('upper_limit_lean_mass_of_left_arm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลไร้ไขมันของแขนซ้าย');
            $table->decimal('lean_mass_percent_of_left_arm')->comment('เปอร์เซ็นต์มวลไร้ไขมันของแขนซ้าย');
            $table->decimal('lean_mass_of_trunk')->comment('มวลไร้ไขมันของลำตัว');
            $table->decimal('lower_limit_lean_mass_of_trunk_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลไร้ไขมันของลำตัว)');
            $table->decimal('upper_limit_lean_mass_of_trunk_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลไร้ไขมันของลำตัว)');
            $table->decimal('lean_mass_percent_of_trunk')->comment('เปอร์เซ็นต์มวลไร้ไขมันของลำตัว');
            $table->decimal('lean_mass_of_right_leg')->comment('มวลไร้ไขมันของขาขวา');
            $table->decimal('lower_limit_lean_mass_of_right_leg_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลไร้ไขมันของขาขวา)');
            $table->decimal('upper_limit_lean_mass_of_right_leg_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลไร้ไขมันของขาขวา)');
            $table->decimal('lean_mass_percent_of_right_leg')->comment('เปอร์เซ็นต์มวลไร้ไขมันของขาขวา');
            $table->decimal('lean_mass_of_left_leg')->comment('มวลไร้ไขมันของขาซ้าย');
            $table->decimal('lower_limit_lean_mass_of_left_leg_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลไร้ไขมันของขาซ้าย)');
            $table->decimal('upper_limit_lean_mass_of_left_leg_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลไร้ไขมันของขาซ้าย)');
            $table->decimal('lean_mass_percent_of_left_leg')->comment('เปอร์เซ็นต์มวลไร้ไขมันของขาซ้าย');
            $table->decimal('tbw_of_right_arm')->comment('น้ำในร่างกายของแขนขวา');
            $table->decimal('lower_limit_tbw_of_right_arm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำในร่างกายของแขนขวา)');
            $table->decimal('upper_limit_tbw_of_right_arm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำในร่างกายของแขนขวา)');
            $table->decimal('tbw_of_left_arm')->comment('น้ำในร่างกายของแขนซ้าย');
            $table->decimal('lower_limit_tbw_of_left_arm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำในร่างกายของแขนซ้าย)');
            $table->decimal('upper_limit_tbw_of_left_arm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำในร่างกายของแขนซ้าย)');
            $table->decimal('tbw_of_trunk')->comment('น้ำในร่างกายของลำตัว');
            $table->decimal('lower_limit_tbw_of_trunk_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำในร่างกายของลำตัว)');
            $table->decimal('upper_limit_tbw_of_trunk_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำในร่างกายของลำตัว)');
            $table->decimal('tbw_of_right_leg')->comment('น้ำในร่างกายของขาขวา');
            $table->decimal('lower_limit_tbw_of_right_leg_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำในร่างกายของขาขวา)');
            $table->decimal('upper_limit_tbw_of_right_leg_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำในร่างกายของขาขวา)');
            $table->decimal('tbw_of_left_leg')->comment('น้ำในร่างกายของขาซ้าย');
            $table->decimal('lower_limit_tbw_of_left_leg_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำในร่างกายของขาซ้าย)');
            $table->decimal('upper_limit_tbw_of_left_leg_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำในร่างกายของขาซ้าย)');
            $table->decimal('icw_of_right_arm')->comment('น้ำภายในเซลล์ของแขนขวา');
            $table->decimal('lower_limit_icw_of_right_arm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายในเซลล์ของแขนขวา)');
            $table->decimal('upper_limit_icw_of_right_arm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายในเซลล์ของแขนขวา)');
            $table->decimal('icw_of_left_arm')->comment('น้ำภายในเซลล์ของแขนซ้าย');
            $table->decimal('lower_limit_icw_of_left_arm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายในเซลล์ของแขนซ้าย)');
            $table->decimal('upper_limit_icw_of_left_arm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายในเซลล์ของแขนซ้าย)');
            $table->decimal('icw_of_trunk')->comment('น้ำภายในเซลล์ของลำตัว');
            $table->decimal('lower_limit_icw_of_trunk_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายในเซลล์ของลำตัว)');
            $table->decimal('upper_limit_icw_of_trunk_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายในเซลล์ของลำตัว)');
            $table->decimal('icw_of_right_leg')->comment('น้ำภายในเซลล์ของขาขวา');
            $table->decimal('lower_limit_icw_of_right_leg_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายในเซลล์ของขาขวา)');
            $table->decimal('upper_limit_icw_of_right_leg_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายในเซลล์ของขาขวา)');
            $table->decimal('icw_of_left_leg')->comment('น้ำภายในเซลล์ของขาซ้าย');
            $table->decimal('lower_limit_icw_of_left_leg_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายในเซลล์ของขาซ้าย)');
            $table->decimal('upper_limit_icw_of_left_leg_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายในเซลล์ของขาซ้าย)');
            $table->decimal('ecw_of_right_arm')->comment('น้ำภายนอกเซลล์ของแขนขวา');
            $table->decimal('lower_limit_ecw_of_right_arm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายนอกเซลล์ของแขนขวา)');
            $table->decimal('upper_limit_ecw_of_right_arm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายนอกเซลล์ของแขนขวา)');
            $table->decimal('ecw_of_left_arm')->comment('น้ำภายนอกเซลล์ของแขนซ้าย');
            $table->decimal('lower_limit_ecw_of_left_arm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายนอกเซลล์ของแขนซ้าย)');
            $table->decimal('upper_limit_ecw_of_left_arm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายนอกเซลล์ของแขนซ้าย)');
            $table->decimal('ecw_of_trunk')->comment('น้ำภายนอกเซลล์ของลำตัว');
            $table->decimal('lower_limit_ecw_of_trunk_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายนอกเซลล์ของลำตัว)');
            $table->decimal('upper_limit_ecw_of_trunk_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายนอกเซลล์ของลำตัว)');
            $table->decimal('ecw_of_right_leg')->comment('น้ำภายนอกเซลล์ของขาขวา');
            $table->decimal('lower_limit_ecw_of_right_leg_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายนอกเซลล์ของขาขวา)');
            $table->decimal('upper_limit_ecw_of_right_leg_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายนอกเซลล์ของขาขวา)');
            $table->decimal('ecw_of_left_leg')->comment('น้ำภายนอกเซลล์ของขาซ้าย');
            $table->decimal('lower_limit_ecw_of_left_leg_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติน้ำภายนอกเซลล์ของขาซ้าย)');
            $table->decimal('upper_limit_ecw_of_left_leg_normal_range')->comment('ค่าสูงสุด (ช่วงปกติน้ำภายนอกเซลล์ของขาซ้าย)');
            $table->decimal('ecw_tbw')->comment('อัตราส่วนน้ำภายนอกเซลล์ต่อน้ำในร่างกายทั้งหมด');
            $table->decimal('ecw_tbw_of_right_arm')->comment('อัตราส่วนน้ำภายนอกเซลล์ต่อน้ำในร่างกายทั้งหมดของแขนขวา');
            $table->decimal('ecw_tbw_of_left_arm')->comment('อัตราส่วนน้ำภายนอกเซลล์ต่อน้ำในร่างกายทั้งหมดของแขนซ้าย');
            $table->decimal('ecw_tbw_of_trunk')->comment('อัตราส่วนน้ำภายนอกเซลล์ต่อน้ำในร่างกายทั้งหมดของลำตัว');
            $table->decimal('ecw_tbw_of_right_leg')->comment('อัตราส่วนน้ำภายนอกเซลล์ต่อน้ำในร่างกายทั้งหมดของขาขวา');
            $table->decimal('ecw_tbw_of_left_leg')->comment('อัตราส่วนน้ำภายนอกเซลล์ต่อน้ำในร่างกายทั้งหมดของขาซ้าย');
            $table->decimal('bfm_of_right_arm')->comment('มวลไขมันของแขนขวา');
            $table->decimal('bfm_percent_of_right_arm')->comment('เปอร์เซ็นต์มวลไขมันของแขนขวา');
            $table->decimal('bfm_of_left_arm')->comment('มวลไขมันของแขนซ้าย');
            $table->decimal('bfm_percent_of_left_arm')->comment('เปอร์เซ็นต์มวลไขมันของแขนซ้าย');
            $table->decimal('bfm_of_trunk')->comment('มวลไขมันของลำตัว');
            $table->decimal('bfm_percent_of_trunk')->comment('เปอร์เซ็นต์มวลไขมันของลำตัว');
            $table->decimal('bfm_of_right_leg')->comment('มวลไขมันของขาขวา');
            $table->decimal('bfm_percent_of_right_leg')->comment('เปอร์เซ็นต์มวลไขมันของขาขวา');
            $table->decimal('bfm_of_left_leg')->comment('มวลไขมันของขาซ้าย');
            $table->decimal('bfm_percent_of_left_leg')->comment('เปอร์เซ็นต์มวลไขมันของขาซ้าย');
            $table->decimal('inbody_score')->comment('คะแนน InBody');
            $table->decimal('target_weight')->comment('น้ำหนักเป้าหมาย');
            $table->decimal('weight_control')->comment('การควบคุมน้ำหนัก');
            $table->decimal('bfm_control')->comment('การควบคุมมวลไขมันในร่างกาย');
            $table->decimal('ffm_control')->comment('การควบคุมมวลไร้ไขมัน');
            $table->decimal('bmr_basal_metabolic_rate')->comment('อัตราการเผาผลาญพลังงานพื้นฐาน');
            $table->decimal('whr_waist_hip_ratio')->comment('อัตราส่วนรอบเอวต่อรอบสะโพก');
            $table->decimal('lower_limit_whr_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติของ WHR)');
            $table->decimal('upper_limit_whr_normal_range')->comment('ค่าสูงสุด (ช่วงปกติของ WHR)');
            $table->decimal('vfl_visceral_fat_level')->comment('ระดับไขมันในช่องท้อง');
            $table->decimal('vfa_visceral_fat_area')->comment('พื้นที่ไขมันในช่องท้อง');
            $table->decimal('obesity_degree')->comment('ระดับความอ้วน');
            $table->decimal('lower_limit_obesity_degree_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติระดับความอ้วน)');
            $table->decimal('upper_limit_obesity_degree_normal_range')->comment('ค่าสูงสุด (ช่วงปกติระดับความอ้วน)');
            $table->decimal('bcm_body_cell_mass')->comment('มวลเซลล์ในร่างกาย');
            $table->decimal('lower_limit_bcm_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลเซลล์ในร่างกาย)');
            $table->decimal('upper_limit_bcm_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลเซลล์ในร่างกาย)');
            $table->decimal('ac_arm_circumference')->comment('เส้นรอบแขน');
            $table->decimal('amc_arm_muscle_circumference')->comment('เส้นรอบกล้ามเนื้อแขน');
            $table->decimal('bmc_bone_mineral_content')->comment('ปริมาณแร่ธาตุในกระดูก');
            $table->decimal('lower_limit_bmc_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติปริมาณแร่ธาตุในกระดูก)');
            $table->decimal('upper_limit_bmc_normal_range')->comment('ค่าสูงสุด (ช่วงปกติปริมาณแร่ธาตุในกระดูก)');
            $table->decimal('tbw_ffm')->comment('อัตราส่วนน้ำในร่างกายทั้งหมดต่อมวลไร้ไขมัน');
            $table->decimal('ffmi_fat_free_mass_index')->comment('ดัชนีมวลไร้ไขมัน');
            $table->decimal('fmi_fat_mass_index')->comment('ดัชนีมวลไขมัน');
            $table->decimal('5khz_ra_phase_angle')->comment('มุมเฟส 5kHz ของแขนขวา');
            $table->decimal('5khz_la_phase_angle')->comment('มุมเฟส 5kHz ของแขนซ้าย');
            $table->decimal('5khz_tr_phase_angle')->comment('มุมเฟส 5kHz ของลำตัว');
            $table->decimal('5khz_rl_phase_angle')->comment('มุมเฟส 5kHz ของขาขวา');
            $table->decimal('5khz_ll_phase_angle')->comment('มุมเฟส 5kHz ของขาซ้าย');
            $table->decimal('50khz_ra_phase_angle')->comment('มุมเฟส 50kHz ของแขนขวา');
            $table->decimal('50khz_la_phase_angle')->comment('มุมเฟส 50kHz ของแขนซ้าย');
            $table->decimal('50khz_tr_phase_angle')->comment('มุมเฟส 50kHz ของลำตัว');
            $table->decimal('50khz_rl_phase_angle')->comment('มุมเฟส 50kHz ของขาขวา');
            $table->decimal('50khz_ll_phase_angle')->comment('มุมเฟส 50kHz ของขาซ้าย');
            $table->decimal('250khz_ra_phase_angle')->comment('มุมเฟส 250kHz ของแขนขวา');
            $table->decimal('250khz_la_phase_angle')->comment('มุมเฟส 250kHz ของแขนซ้าย');
            $table->decimal('250khz_tr_phase_angle')->comment('มุมเฟส 250kHz ของลำตัว');
            $table->decimal('250khz_rl_phase_angle')->comment('มุมเฟส 250kHz ของขาขวา');
            $table->decimal('250khz_ll_phase_angle')->comment('มุมเฟส 250kHz ของขาซ้าย');
            $table->decimal('50khz_whole_body_phase_angle')->comment('มุมเฟส 50kHz ของร่างกายทั้งหมด');
            $table->decimal('measured_circumference_of_neck')->comment('เส้นรอบคอที่วัดได้');
            $table->decimal('measured_circumference_of_chest')->comment('เส้นรอบอกที่วัดได้');
            $table->decimal('measured_circumference_of_abdomen')->comment('เส้นรอบท้องที่วัดได้');
            $table->decimal('measured_circumference_of_hip')->comment('เส้นรอบสะโพกที่วัดได้');
            $table->decimal('measured_circumference_of_right_arm')->comment('เส้นรอบแขนขวาที่วัดได้');
            $table->decimal('measured_circumference_of_left_arm')->comment('เส้นรอบแขนซ้ายที่วัดได้');
            $table->decimal('measured_circumference_of_right_thigh')->comment('เส้นรอบต้นขาขวาที่วัดได้');
            $table->decimal('measured_circumference_of_left_thigh')->comment('เส้นรอบต้นขาซ้ายที่วัดได้');
            $table->decimal('growth_score')->comment('คะแนนการเจริญเติบโต');
            $table->decimal('obesity_degree_of_a_child')->comment('ระดับความอ้วนของเด็ก');
            $table->decimal('lower_limit_obesity_degree_of_a_child_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติระดับความอ้วนของเด็ก)');
            $table->decimal('upper_limit_obesity_degree_of_a_child_normal_range')->comment('ค่าสูงสุด (ช่วงปกติระดับความอ้วนของเด็ก)');
            $table->decimal('systolic')->comment('ความดันโลหิตซิสโตลิก');
            $table->decimal('diastolic')->comment('ความดันโลหิตไดแอสโตลิก');
            $table->decimal('pulse')->comment('ชีพจร');
            $table->decimal('mean_artery_pressure')->comment('ความดันโลหิตเฉลี่ย');
            $table->decimal('pulse_pressure')->comment('ความดันชีพจร');
            $table->decimal('rate_pressure_product')->comment('อัตราส่วนความดันต่ออัตราการเต้นของหัวใจ');
            $table->decimal('smi')->comment('ดัชนีมวลกล้ามเนื้อโครงร่าง');
            $table->decimal('recommended_calorie_intake')->comment('ปริมาณแคลอรี่ที่แนะนำ');
            $table->decimal('lower_limit_bmr_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติของ BMR)');
            $table->decimal('upper_limit_bmr_normal_range')->comment('ค่าสูงสุด (ช่วงปกติของ BMR)');
            $table->decimal('smi_asm_ht2_t_score')->comment('คะแนน T-score ของ SMI (มวลกล้ามเนื้อโครงร่างต่อส่วนสูงกำลังสอง)');
            $table->decimal('smi_asm_ht2_z_score')->comment('คะแนน Z-score ของ SMI (มวลกล้ามเนื้อโครงร่างต่อส่วนสูงกำลังสอง)');
            $table->decimal('whole_body_ecw_tbw_t_score')->comment('คะแนน T-score ของ ECW/TBW ทั้งร่างกาย');
            $table->decimal('whole_body_ecw_tbw_z_score')->comment('คะแนน Z-score ของ ECW/TBW ทั้งร่างกาย');
            $table->decimal('vfa_t_score')->comment('คะแนน T-score ของพื้นที่ไขมันในช่องท้อง (VFA)');
            $table->decimal('vfa_z_score')->comment('คะแนน Z-score ของพื้นที่ไขมันในช่องท้อง (VFA)');
            $table->decimal('bmi_t_score')->comment('คะแนน T-score ของดัชนีมวลกาย (BMI)');
            $table->decimal('bmi_z_score')->comment('คะแนน Z-score ของดัชนีมวลกาย (BMI)');
            $table->decimal('subcutaneous_fat')->comment('ไขมันใต้ผิวหนัง');
            $table->decimal('arms_legs_fat')->comment('ไขมันแขน/ขา');
            $table->decimal('lower_limit_subcutaneous_fat_of_abdomen_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติไขมันใต้ผิวหนังบริเวณช่องท้อง)');
            $table->decimal('upper_limit_subcutaneous_fat_of_abdomen_normal_range')->comment('ค่าสูงสุด (ช่วงปกติไขมันใต้ผิวหนังบริเวณช่องท้อง)');
            $table->decimal('visceral_fat')->comment('ไขมันในช่องท้อง');
            $table->decimal('lower_limit_visceral_fat_of_abdomen_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติไขมันในช่องท้องบริเวณช่องท้อง)');
            $table->decimal('upper_limit_visceral_fat_of_abdomen_normal_range')->comment('ค่าสูงสุด (ช่วงปกติไขมันในช่องท้องบริเวณช่องท้อง)');
            $table->decimal('lower_limit_bfm_of_arm_leg_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลไขมันของแขนและขา)');
            $table->decimal('upper_limit_bfm_of_arm_leg_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลไขมันของแขนและขา)');
            $table->decimal('lower_limit_bfm_of_trunk_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติมวลไขมันของลำตัว)');
            $table->decimal('upper_limit_bfm_of_trunk_normal_range')->comment('ค่าสูงสุด (ช่วงปกติมวลไขมันของลำตัว)');
            $table->decimal('abdominal_fat')->comment('ไขมันช่องท้อง');
            $table->decimal('v_s_ratio')->comment('อัตราส่วน V/S (อัตราส่วนพื้นที่ไขมันในช่องท้องต่อพื้นที่ไขมันใต้ผิวหนัง)');
            $table->decimal('sfa')->comment('พื้นที่ไขมันใต้ผิวหนัง');
            $table->decimal('whtr')->comment('อัตราส่วนรอบเอวต่อส่วนสูง');
            $table->decimal('bai')->comment('ดัชนีความอ้วนของร่างกาย');
            $table->decimal('absi')->comment('ดัชนีรูปร่างร่างกาย');
            $table->decimal('conicity_index')->comment('ดัชนีความกรวย');
            $table->decimal('svr')->comment('อัตราส่วนมวลกล้ามเนื้อโครงร่างต่อพื้นที่ไขมันในช่องท้อง');
            $table->decimal('upper_limit_whtr_normal_range')->comment('ค่าสูงสุด (ช่วงปกติของ WHtR)');
            $table->decimal('upper_limit_bai_normal_range')->comment('ค่าสูงสุด (ช่วงปกติของ BAI)');
            $table->decimal('upper_limit_absi_normal_range')->comment('ค่าสูงสุด (ช่วงปกติของ ABSI)');
            $table->decimal('upper_limit_conicity_index_normal_range')->comment('ค่าสูงสุด (ช่วงปกติของ Conicity Index)');
            $table->decimal('upper_limit_svr_normal_range')->comment('ค่าสูงสุด (ช่วงปกติของ SVR)');
            $table->decimal('50khz_ab_impedance')->comment('ความต้านทานไฟฟ้า 50kHz ของช่องท้อง');
            $table->decimal('250khz_ab_impedance')->comment('ความต้านทานไฟฟ้า 250kHz ของช่องท้อง');
            $table->decimal('wc')->comment('เส้นรอบเอว');
            $table->decimal('angle_r')->comment('มุม R');
            $table->decimal('angle_l')->comment('มุม L');
            $table->decimal('lower_limit_abdominal_fat_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติไขมันช่องท้อง)');
            $table->decimal('upper_limit_abdominal_fat_normal_range')->comment('ค่าสูงสุด (ช่วงปกติไขมันช่องท้อง)');
            $table->decimal('impedance_check')->comment('การตรวจสอบความต้านทานไฟฟ้า');
            $table->decimal('systolic2')->comment('ความดันโลหิตซิสโตลิก 2');
            $table->decimal('diastolic2')->comment('ความดันโลหิตไดแอสโตลิก 2');
            $table->decimal('pulse2')->comment('ชีพจร 2');
            $table->decimal('mean_artery_pressure2')->comment('ความดันโลหิตเฉลี่ย 2');
            $table->decimal('pulse_pressure2')->comment('ความดันชีพจร 2');
            $table->decimal('rate_pressure_product2')->comment('อัตราส่วนความดันต่ออัตราการเต้นของหัวใจ 2');
            $table->decimal('lower_limit_measured_circumference_of_waist_normal_range')->comment('ค่าต่ำสุด (ช่วงปกติเส้นรอบเอวที่วัดได้)');
            $table->decimal('upper_limit_measured_circumference_of_waist_normal_range')->comment('ค่าสูงสุด (ช่วงปกติเส้นรอบเอวที่วัดได้)');
            $table->decimal('smm_wt')->comment('อัตราส่วนมวลกล้ามเนื้อโครงร่างต่อน้ำหนัก');
            $table->decimal('bfm_whole_body_percent')->comment('เปอร์เซ็นต์มวลไขมันของร่างกายทั้งหมด');
            $table->decimal('z_r_ht')->comment('Z (ความต้านทานไฟฟ้า/ส่วนสูง)');
            $table->decimal('z_xc_ht')->comment('Z (ความต้านทานไฟฟ้าเชิงขั้ว/ส่วนสูง)');
            $table->decimal('r_ht')->comment('ความต้านทานไฟฟ้า/ส่วนสูง');
            $table->decimal('xc_ht')->comment('ความต้านทานไฟฟ้าเชิงขั้ว/ส่วนสูง');
            $table->decimal('ecm_bcm')->comment('อัตราส่วนมวลสารภายนอกเซลล์ต่อมวลเซลล์ในร่างกาย');
            $table->decimal('tbw_wt')->comment('อัตราส่วนน้ำในร่างกายทั้งหมดต่อน้ำหนัก');
            $table->decimal('bcm_t_score')->comment('คะแนน T-score ของมวลเซลล์ในร่างกาย (BCM)');
            $table->decimal('bcm_z_score')->comment('คะแนน Z-score ของมวลเซลล์ในร่างกาย (BCM)');
            $table->decimal('ffmi_t_score')->comment('คะแนน T-score ของดัชนีมวลไร้ไขมัน (FFMI)');
            $table->decimal('ffmi_z_score')->comment('คะแนน Z-score ของดัชนีมวลไร้ไขมัน (FFMI)');
            $table->decimal('fmi_t_score')->comment('คะแนน T-score ของดัชนีมวลไขมัน (FMI)');
            $table->decimal('fmi_z_score')->comment('คะแนน Z-score ของดัชนีมวลไขมัน (FMI)');
            $table->decimal('pbf_t_score')->comment('คะแนน T-score ของเปอร์เซ็นต์ไขมันในร่างกาย (PBF)');
            $table->decimal('pbf_z_score')->comment('คะแนน Z-score ของเปอร์เซ็นต์ไขมันในร่างกาย (PBF)');
            $table->decimal('weight_t_score')->comment('คะแนน T-score ของน้ำหนัก');
            $table->decimal('weight_z_score')->comment('คะแนน Z-score ของน้ำหนัก');
            $table->decimal('whr_t_score')->comment('คะแนน T-score ของอัตราส่วนรอบเอวต่อรอบสะโพก (WHR)');
            $table->decimal('whr_z_score')->comment('คะแนน Z-score ของอัตราส่วนรอบเอวต่อรอบสะโพก (WHR)');
            $table->decimal('50khz_whole_body_phase_angle_t_score')->comment('คะแนน T-score ของมุมเฟส 50kHz ทั้งร่างกาย');
            $table->decimal('50khz_whole_body_phase_angle_z_score')->comment('คะแนน Z-score ของมุมเฟส 50kHz ทั้งร่างกาย');
            $table->decimal('tbw_wt_t_score')->comment('คะแนน T-score ของอัตราส่วนน้ำในร่างกายทั้งหมดต่อน้ำหนัก');
            $table->decimal('tbw_wt_z_score')->comment('คะแนน Z-score ของอัตราส่วนน้ำในร่างกายทั้งหมดต่อน้ำหนัก');
            $table->decimal('smm_wt_t_score')->comment('คะแนน T-score ของอัตราส่วนมวลกล้ามเนื้อโครงร่างต่อน้ำหนัก');
            $table->decimal('smm_wt_z_score')->comment('คะแนน Z-score ของอัตราส่วนมวลกล้ามเนื้อโครงร่างต่อน้ำหนัก');
            $table->decimal('ecm_bcm_t_score')->comment('คะแนน T-score ของอัตราส่วนมวลสารภายนอกเซลล์ต่อมวลเซลล์ในร่างกาย');
            $table->decimal('ecm_bcm_z_score')->comment('คะแนน Z-score ของอัตราส่วนมวลสารภายนอกเซลล์ต่อมวลเซลล์ในร่างกาย');
            $table->decimal('left_hand_grip1')->comment('แรงบีบมือซ้าย 1');
            $table->decimal('left_hand_grip2')->comment('แรงบีบมือซ้าย 2');
            $table->decimal('right_hand_grip1')->comment('แรงบีบมือขวา 1');
            $table->decimal('right_hand_grip2')->comment('แรงบีบมือขวา 2');
            $table->decimal('adjusted_ffm')->comment('มวลไร้ไขมันที่ปรับแล้ว');
            $table->decimal('adjusted_smi')->comment('ดัชนีมวลกล้ามเนื้อโครงร่างที่ปรับแล้ว');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('inbodies');
    }
};
